spring.application.name=wealth-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/wealth
spring.datasource.username=wealth
spring.datasource.password=wealth

spring.jpa.hibernate.ddl-auto=validate
